### ISSUE TITLE
Addition of sign in page, login page with authentication for patients and doctors

### ISSUE THREAD

**Issue by archita-2810** [yazdanhaider/Hospital-Management#10]

**Comment by archita-2810** [comment]
@yazdanhaider please kindly assign me with this issue, also do add the hactoberfest label, thank you.

**Comment by yazdanhaider** [comment]
> @yazdanhaider please kindly assign me with this issue, also do add the hactoberfest label, thank you.

Heyyyy, I’ve already assigned the task for the sign-up page, but no worries! Since you’re working on both the sign-up and login pages with authentication, please ensure there are separate login options for patients and doctors. Also make sure to enhanced the user interface of both pages. 

Go ahead and contribute!!👍🏻
